### ISSUE TITLE
It is not possible to Upload a Document 

### ISSUE THREAD

**Issue by VitoAlbano** [Alfresco/alfresco-ng2-components#411]
Try to upload a file into document list
Nothing is uploaded

An error is showed on console : 

zone.js:260 Uncaught EXCEPTION: Error in http://localhost:3000/node_modules/ng2-alfresco-upload/dist/src/components/upload-button.component.html:19:19
ORIGINAL EXCEPTION: Attempt to use a destroyed view: detectChanges
ORIGINAL STACKTRACE:
Error: Attempt to use a destroyed view: detectChanges
    at ViewDestroyedException.BaseException [as constructor] (http://localhost:3000/node_modules/@angular/core//bundles/core.umd.js:4383:27)
    at new ViewDestroyedException (http://localhost:3000/node_modules/@angular/core//bundles/core.umd.js:8482:20)
    at DebugAppView.AppView.throwDestroyedError (http://localhost:3000/node_modules/@angular/core//bundles/core.umd.js:11928:76)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/node_modules/@angular/core//bundles/core.umd.js:11875:22)
    at DebugAppView.detectChanges (http://localhost:3000/node_modules/@angular/core//bundles/core.umd.js:11981:48)
    at ViewRef_.detectChanges (http://localhost:3000/node_modules/@angular/core//bundles/core.umd.js:10202:69)
    at SafeSubscriber.eval [as _next] (http://localhost:3000/node_modules/ng2-alfresco-upload/dist/src/components/file-uploading-dialog.component.js:62:42)
    at SafeSubscriber.__tryOrUnsub (http://localhost:3000/node_modules/rxjs/Subscriber.js:225:16)
    at SafeSubscriber.next (http://localhost:3000/node_modules/rxjs/Subscriber.js:174:22)
    at Subscriber._next (http://localhost:3000/node_modules/rxjs/Subscriber.js:124:26)
ERROR CONTEXT:
[object Object]

**Comment by VitoAlbano** [comment]
Issue Update : 

1.Login into Demo app
2.Try to upload a .pdf file 
3.Notice that the file is not uploaded
4.Try to upload .doc file
5.Notice that the file is correctly uploaded
6.Notice that the .pdf file is now visible on document list
