### ISSUE TITLE
Testing IE 11 on Windows 8.1  

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#930]
- [x] **Login component** Can login with to BPM with CSRF enabled 
- [x]  **Upload component** Folder upload not supported (http://answers.microsoft.com/en-us/msoffice/forum/all/upload-folders-in-internet-explorer/0aeee804-dd7a-4b8f-bf1d-40eec43c231c)
- [x] **File preview component** PDF viewer does not display with below error

```
`Error: No PDFJS.workerSrc specified
   DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
   File: home
   Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
   Error: No PDFJS.workerSrc specified
      at error (http://localhost:3000/node_modules/pdfjs-dist/build/pdf.js:291:5)
   at getWorkerSrc (http://localhost:3000/node_modules/pdfjs-dist/build/pdf.js:9584:5)
   at PDFWorker_initialize (http://localhost:3000/node_modules/pdfjs-dist/build/pdf.js:9647:9)
   at PDFWorker (http://localhost:3000/node_modules/pdfjs-dist/build/pdf.js:9623:5)
   at getDocument (http://localhost:3000/node_modules/pdfjs-dist/build/pdf.js:8772:5)
   at Anonymous function (eval code:46:17)
   at ZoneAwarePromise (http://localhost:3000/node_modules/zone.js/dist/zone.js:518:29)
   at ngOnChanges (eval code:45:13)
   at detectChangesInternal (Function code:838:29)`
```
- [x] **Activiti form component** People, comment and checklist dialogs do not appear
- [x] **Activiti form component** #802 also an issue with IE 11
- [x] **Activiti form component** date picker does not display with error in console

```
EXCEPTION: Error in http://localhost:3000/node_modules/ng2-activiti-form/dist/src/components/widgets/date/date.widget.html:20:12 caused by: Object doesn't support this action
   ORIGINAL EXCEPTION: Object doesn't support this action
   ORIGINAL STACKTRACE:
   TypeError: Object doesn't support this action
   at value (http://localhost:3000/node_modules/md-date-time-picker/dist/js/mdDateTimePicker.min.js:1:19704)
   at value (http://localhost:3000/node_modules/md-date-time-picker/dist/js/mdDateTimePicker.min.js:1:10295)
   at value (http://localhost:3000/node_modules/md-date-time-picker/dist/js/mdDateTimePicker.min.js:1:1498)
   at _handle_click_17_0 (Function code:315:3)
   at Anonymous function (eval code:9698:21)
   at Anonymous function (eval code:1877:13)
   at Anonymous function (eval code:1990:108)
   at invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:230:13)
   at onInvoke (eval code:6242:25)
   at invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:230:13)
   ERROR CONTEXT:
   [object Object]
   SCRIPT5022: Error: Error in http://localhost:3000/node_modules/ng2-activiti-form/dist/src/components/widgets/date/date.widget.html:20:12 caused by: Object doesn't support this action
   File: zone.js, Line: 158, Column: 25`
- People and group of people do not display suggestions
ORIGINAL EXCEPTION: InvalidStateError
ORIGINAL STACKTRACE:
Error: Error in http://localhost:3000/node_modules/ng2-activiti-form/dist/src/components/widgets/people/people.widget.html:7:11 caused by: InvalidStateError
at _rethrowWithContext (eval code:9688:21)
at Anonymous function (eval code:9701:21)
at Anonymous function (eval code:1877:13)
at Anonymous function (eval code:1990:108)
at invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:230:13)
at onInvoke (eval code:6242:25)
at invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:230:13)
at runGuarded (http://localhost:3000/node_modules/zone.js/dist/zone.js:128:21)
at runInnerGuarded (eval code:6271:64)
at runGuarded (eval code:6504:55)
ERROR CONTEXT:
[object Object]
SCRIPT5022: Error: Error in http://localhost:3000/node_modules/ng2-activiti-form/dist/src/components/widgets/people/people.widget.html:7:11 caused by: InvalidStateError
File: zone.js, Line: 158, Column: 25
```

**Comment by DenisVuyka** [comment]
Date Picker requires additional polyfills depending on the version of IE:
<img width="568" alt="screen shot 2016-10-31 at 12 07 58" src="https://cloud.githubusercontent.com/assets/503991/19853700/c97a02b6-9f62-11e6-9ee5-6044f1abeed3.png">
