### ISSUE TITLE
Testing IE 10 on Windows 8

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#932]
Demo shell does not load

<img width="1323" alt="windows 8 ie 10" src="https://cloud.githubusercontent.com/assets/13200338/19746679/6423caa0-9bcf-11e6-8552-ee2ec5edc7f6.png">

```
EXCEPTION: Error in ./AppComponent class AppComponent_Host - inline template:0:0 caused by: Unable to get property 'split' of undefined or null reference 
ORIGINAL EXCEPTION: Unable to get property 'split' of undefined or null reference 
ORIGINAL STACKTRACE: 
TypeError: Unable to get property 'split' of undefined or null reference
   at AlfrescoTranslationService (eval code:33:9)
   at get (Function code:205:58)
   at getInternal (Function code:532:55)
   at get (eval code:7221:13)
   at createInternal (Function code:14:3)
   at create (eval code:9419:13)
   at create (eval code:9631:17)
   at create (eval code:6029:13)
   at bootstrap (eval code:7051:13)
   at Anonymous function (eval code:6960:79) 
ERROR CONTEXT: 
[object Object] 
Unhandled Promise rejection:Error in ./AppComponent class AppComponent_Host - inline template:0:0 caused by: Unable to get property 'split' of undefined or null reference; Zone:<root>; Task:Promise.then; Value:Error: Error in ./AppComponent class AppComponent_Host - inline template:0:0 caused by: Unable to get property 'split' of undefined or null referenceError: Error in ./AppComponent class AppComponent_Host - inline template:0:0 caused by: Unable to get property 'split' of undefined or null reference
   at _rethrowWithContext (eval code:9688:21)
   at create (eval code:9634:17)
   at create (eval code:6029:13)
   at bootstrap (eval code:7051:13)
   at Anonymous function (eval code:6960:79)
   at _moduleDoBootstrap (eval code:6960:17)
   at Anonymous function (eval code:6928:25)
   at invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:230:13)
   at onInvoke (eval code:6242:25)
   at invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:230:13) 
Error: Uncaught (in promise): Error: Error in ./AppComponent class AppComponent_Host - inline template:0:0 caused by: Unable to get property 'split' of undefined or null reference
Error: Error in ./AppComponent class AppComponent_Host - inline template:0:0 caused by: Unable to get property 'split' of undefined or null reference
   at _rethrowWithContext (eval code:9688:21)
   at create (eval code:9634:17)
   at create (eval code:6029:13)
   at bootstrap (eval code:7051:13)
   at Anonymous function (eval code:6960:79)
   at _moduleDoBootstrap (eval code:6960:17)
   at Anonymous function (eval code:6928:25)
   at invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:230:13)
   at onInvoke (eval code:6242:25)
   at invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:230:13) 
```

**Comment by hashraf88** [comment]
- [ ] **Login component** When logging into ECM error login does not occur and error occurs

```
EXCEPTION: Object doesn't support property or method 'convertToType' 
ORIGINAL STACKTRACE: 
TypeError: Object doesn't support property or method 'convertToType'
   at constructFromObject (eval code:73990:9)
   at constructFromObject (eval code:73928:9)
   at convertToType (eval code:74572:11)
   at deserialize (eval code:74447:5)
   at Anonymous function (eval code:89902:29)
   at callback (eval code:51902:3)
   at Anonymous function (eval code:51543:7)
   at emit (eval code:8196:7)
   at onreadystatechange (eval code:51984:5)
   at wrapFn (http://localhost:3000/node_modules/zone.js/dist/zone.js:698:17) 
SCRIPT438: Object doesn't support property or method 'convertToType' 
login, line 227 character 13
```

**Comment by hashraf88** [comment]
When trying to login to either BPM or ECM the below error occurs and no login occurs

<img width="1078" alt="screen shot 2016-12-05 at 21 01 39" src="https://cloud.githubusercontent.com/assets/13200338/20902258/3c75b166-bb2e-11e6-8904-936ef931a37d.png">

**Comment by hashraf88** [comment]
When trying to access the demo shell the below occurs
<img width="941" alt="screen shot 2016-12-13 at 20 10 28" src="https://cloud.githubusercontent.com/assets/13200338/21157140/4dde3d04-c170-11e6-9229-54138495b28b.png">

```
SCRIPT1002: Syntax error 
app.js, line 541 character 2
```

**Comment by hashraf88** [comment]
1. Login background is too long
<img width="375" alt="screen shot 2017-01-03 at 16 02 30" src="https://cloud.githubusercontent.com/assets/13200338/21613679/29c43edc-d1ce-11e6-9374-f573202638e4.png">

**Comment by hashraf88** [comment]
Demo shell does not load with below displayed
<img width="1388" alt="screen shot 2017-01-04 at 09 31 19" src="https://cloud.githubusercontent.com/assets/13200338/21637851/c36dad60-d260-11e6-944e-e132e1e596cd.png">

**Full error in console:**

`Unhandled Promise rejection:Template parse errors:
Can't bind to 'providers' since it isn't a known property of 'alfresco-login'.
1. If 'alfresco-login' is an Angular component and it has 'providers' input, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("

<alfresco-login #alfrescologin
                [ERROR ->][providers]="providers"
                [fieldsValidation]="customValidation"
                [disabl"): LoginDemoComponent@40:16
Can't bind to 'fieldsValidation' since it isn't a known property of 'alfresco-login'.
1. If 'alfresco-login' is an Angular component and it has 'fieldsValidation' input, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
<alfresco-login #alfrescologin
                [providers]="providers"
                [ERROR ->][fieldsValidation]="customValidation"
                [disableCsrf]="disableCsrf"
                (ex"): LoginDemoComponent@41:16
Can't bind to 'disableCsrf' since it isn't a known property of 'alfresco-login'.
1. If 'alfresco-login' is an Angular component and it has 'disableCsrf' input, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("      [providers]="providers"
                [fieldsValidation]="customValidation"
                [ERROR ->][disableCsrf]="disableCsrf"
                (executeSubmit)="validateForm($event)"
                (o"): LoginDemoComponent@42:16
'alfresco-login' is not a known element:
1. If 'alfresco-login' is an Angular component, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("


[ERROR ->]<alfresco-login #alfrescologin
                [providers]="providers"
                [fieldsValidat"): LoginDemoComponent@39:0; Zone:<root>; Task:Promise.then; Value:Error: Template parse errors:
Can't bind to 'providers' since it isn't a known property of 'alfresco-login'.
1. If 'alfresco-login' is an Angular component and it has 'providers' input, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("

<alfresco-login #alfrescologin
                [ERROR ->][providers]="providers"
                [fieldsValidation]="customValidation"
                [disabl"): LoginDemoComponent@40:16
Can't bind to 'fieldsValidation' since it isn't a known property of 'alfresco-login'.
1. If 'alfresco-login' is an Angular component and it has 'fieldsValidation' input, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
<alfresco-login #alfrescologin
                [providers]="providers"
                [ERROR ->][fieldsValidation]="customValidation"
                [disableCsrf]="disableCsrf"
                (ex"): LoginDemoComponent@41:16
Can't bind to 'disableCsrf' since it isn't a known property of 'alfresco-login'.
1. If 'alfresco-login' is an Angular component and it has 'disableCsrf' input, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("      [providers]="providers"
                [fieldsValidation]="customValidation"
                [ERROR ->][disableCsrf]="disableCsrf"
                (executeSubmit)="validateForm($event)"
                (o"): LoginDemoComponent@42:16
'alfresco-login' is not a known element:
1. If 'alfresco-login' is an Angular component, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("


[ERROR ->]<alfresco-login #alfrescologin
                [providers]="providers"
                [fieldsValidat"): LoginDemoComponent@39:0Error: Template parse errors:
Can't bind to 'providers' since it isn't a known property of 'alfresco-login'.
1. If 'alfresco-login' is an Angular component and it has 'providers' input, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("

<alfresco-login #alfrescologin
                [ERROR ->][providers]="providers"
                [fieldsValidation]="customValidation"
                [disabl"): LoginDemoComponent@40:16
Can't bind to 'fieldsValidation' since it isn't a known property of 'alfresco-login'.
1. If 'alfresco-login' is an Angular component and it has 'fieldsValidation' input, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
<alfresco-login #alfrescologin
                [providers]="providers"
                [ERROR ->][fieldsValidation]="customValidation"
                [disableCsrf]="disableCsrf"
                (ex"): LoginDemoComponent@41:16
Can't bind to 'disableCsrf' since it isn't a known property of 'alfresco-login'.
1. If 'alfresco-login' is an Angular component and it has 'disableCsrf' input, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("      [providers]="providers"
                [fieldsValidation]="customValidation"
                [ERROR ->][disableCsrf]="disableCsrf"
                (executeSubmit)="validateForm($event)"
                (o"): LoginDemoComponent@42:16
'alfresco-login' is not a known element:
1. If 'alfresco-login' is an Angular component, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("


[ERROR ->]<alfresco-login #alfrescologin
                [providers]="providers"
                [fieldsValidat"): LoginDemoComponent@39:0
   at parse (eval code:7730:15)
   at _compileTemplate (eval code:17576:11)
   at Anonymous function (eval code:17496:51)
   at forEach (eval code:72:11)
   at _compileComponents (eval code:17496:11)
   at createResult (eval code:17392:15)
   at invoke (eval code:227:13)
   at run (eval code:113:17)
   at Anonymous function (eval code:509:17)
   at invokeTask (eval code:260:17)
   at runTask (eval code:151:21)
   at drainMicroTaskQueue (eval code:405:25)
   at invoke (eval code:336:25)
   at Anonymous function (eval code:1149:13) 
Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'providers' since it isn't a known property of 'alfresco-login'.
1. If 'alfresco-login' is an Angular component and it has 'providers' input, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("

<alfresco-login #alfrescologin
                [ERROR ->][providers]="providers"
                [fieldsValidation]="customValidation"
                [disabl"): LoginDemoComponent@40:16
Can't bind to 'fieldsValidation' since it isn't a known property of 'alfresco-login'.
1. If 'alfresco-login' is an Angular component and it has 'fieldsValidation' input, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
<alfresco-login #alfrescologin
                [providers]="providers"
                [ERROR ->][fieldsValidation]="customValidation"
                [disableCsrf]="disableCsrf"
                (ex"): LoginDemoComponent@41:16
Can't bind to 'disableCsrf' since it isn't a known property of 'alfresco-login'.
1. If 'alfresco-login' is an Angular component and it has 'disableCsrf' input, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("      [providers]="providers"
                [fieldsValidation]="customValidation"
                [ERROR ->][disableCsrf]="disableCsrf"
                (executeSubmit)="validateForm($event)"
                (o"): LoginDemoComponent@42:16
'alfresco-login' is not a known element:
1. If 'alfresco-login' is an Angular component, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("


[ERROR ->]<alfresco-login #alfrescologin
                [providers]="providers"
                [fieldsValidat"): LoginDemoComponent@39:0
Error: Template parse errors:
Can't bind to 'providers' since it isn't a known property of 'alfresco-login'.
1. If 'alfresco-login' is an Angular component and it has 'providers' input, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("

<alfresco-login #alfrescologin
                [ERROR ->][providers]="providers"
                [fieldsValidation]="customValidation"
                [disabl"): LoginDemoComponent@40:16
Can't bind to 'fieldsValidation' since it isn't a known property of 'alfresco-login'.
1. If 'alfresco-login' is an Angular component and it has 'fieldsValidation' input, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
<alfresco-login #alfrescologin
                [providers]="providers"
                [ERROR ->][fieldsValidation]="customValidation"
                [disableCsrf]="disableCsrf"
                (ex"): LoginDemoComponent@41:16
Can't bind to 'disableCsrf' since it isn't a known property of 'alfresco-login'.
1. If 'alfresco-login' is an Angular component and it has 'disableCsrf' input, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("      [providers]="providers"
                [fieldsValidation]="customValidation"
                [ERROR ->][disableCsrf]="disableCsrf"
                (executeSubmit)="validateForm($event)"
                (o"): LoginDemoComponent@42:16
'alfresco-login' is not a known element:
1. If 'alfresco-login' is an Angular component, then verify that it is part of this module.
2. If 'alfresco-login' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("


[ERROR ->]<alfresco-login #alfrescologin
                [providers]="providers"
                [fieldsValidat"): LoginDemoComponent@39:0
   at parse (eval code:7730:15)
   at _compileTemplate (eval code:17576:11)
   at Anonymous function (eval code:17496:51)
   at forEach (eval code:72:11)
   at _compileComponents (eval code:17496:11)
   at createResult (eval code:17392:15)
   at invoke (eval code:227:13)
   at run (eval code:113:17)
   at Anonymous function (eval code:509:17)
   at invokeTask (eval code:260:17)
   at runTask (eval code:151:21)
   at drainMicroTaskQueue (eval code:405:25)
   at invoke (eval code:336:25)
   at Anonymous function (eval code:1149:13) 
`

**Comment by hashraf88** [comment]
1. Login not displayed correctly
<img width="430" alt="screen shot 2017-01-05 at 11 43 43" src="https://cloud.githubusercontent.com/assets/13200338/21679476/49a22150-d33c-11e6-99bc-8c2180f25dac.png">

n.b. testing still occuring

**Comment by hashraf88** [comment]
Testing completed with above issues, as mentioned can not test Process or Report components.
